In [369]:
#!/usr/bin/python3
# -*- coding: utf-8 -*-
'''
Author yangjie @ SUSTC
'''








0.25
0.5
1
1.5
2


In [417]:
cimg=GammaCorrect(img,gamma)
I.save(cimg,'gamma_'+str(int(0.25*100)))

array([[73.60392157, 72.53333333, 69.36862745, ..., 82.45098039,
        85.89803922, 50.96470588],
       [73.60392157, 72.53333333, 69.36862745, ..., 82.45098039,
        85.89803922, 50.96470588],
       [74.68235294, 69.36862745, 70.41568627, ..., 69.36862745,
        61.2745098 , 29.68235294],
       ...,
       [ 3.0745098 ,  3.0745098 ,  3.29803922, ..., 11.01568627,
        15.0745098 , 13.65098039],
       [ 1.56862745,  2.45098039,  2.65098039, ..., 16.0627451 ,
        18.67058824, 16.56862745],
       [ 1.89803922,  3.52941176,  2.45098039, ..., 19.76862745,
        18.13333333, 20.32941176]])

In [256]:
cvimg=cv2.blur(np.uint8(img),mask.shape);
I.save(cvimg, mark='opencvmean');
rimg=MaskFiltering(img,mask)

In [306]:

rimg

array([[135.22222222, 134.55555556, 135.33333333, ..., 118.11111111,
        134.        , 128.77777778],
       [134.44444444, 133.55555556, 134.22222222, ..., 106.11111111,
        109.77777778,  99.44444444],
       [132.88888889, 132.22222222, 132.66666667, ...,  83.        ,
         74.22222222,  61.77777778],
       ...,
       [ 28.33333333,  28.77777778,  30.33333333, ...,  36.22222222,
         40.22222222,  48.        ],
       [ 26.33333333,  27.33333333,  29.66666667, ...,  44.55555556,
         50.88888889,  57.44444444],
       [ 25.88888889,  27.11111111,  28.55555556, ...,  53.22222222,
         60.33333333,  64.77777778]])

In [298]:
rimg

array([[135.22222222, 134.55555556, 135.33333333, ..., 118.11111111,
        134.        , 128.77777778],
       [134.44444444, 133.55555556, 134.22222222, ..., 106.11111111,
        109.77777778,  99.44444444],
       [132.88888889, 132.22222222, 132.66666667, ...,  83.        ,
         74.22222222,  61.77777778],
       ...,
       [ 28.33333333,  28.77777778,  30.33333333, ...,  36.22222222,
         40.22222222,  48.        ],
       [ 26.33333333,  27.33333333,  29.66666667, ...,  44.55555556,
         50.88888889,  57.44444444],
       [ 25.88888889,  27.11111111,  28.55555556, ...,  53.22222222,
         60.33333333,  64.77777778]])

In [283]:
ROI=img[0:3,1:4]
val=ROI*mask
np.mean(val)


134.55555555555554

In [385]:
 P5( ['lena', 'bridge', 'circles','fingerprint1'])

please input mask, 
 split with , for items 		 ; for rows 
1,1,1;1,1,1;1,1,1
mask is: 
 [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
